#!/bin/bash
set -e
# "set -e" to exit on error (avoids snowballing)

apt-get install -y git

mkdir -p /opt/iiab

# Get the extras
cd /opt/iiab
git clone https://github.com/jvonau/iiab-upgrader --depth 1

/opt/iiab/iiab-upgrader/iiab-upgrade

